import os
import json
from datetime import datetime

class OutputEngine:
    def __init__(self, output_dir="prob/output/files"):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_txt(self, filename, content):
        path = os.path.join(self.output_dir, filename + ".txt")
        with open(path, "w") as f:
            f.write(content)
        return path

    def generate_json(self, filename, data):
        path = os.path.join(self.output_dir, filename + ".json")
        with open(path, "w") as f:
            json.dump(data, f, indent=2)
        return path

    def generate_research_report(self, title, scenario, result, memory_notes):
        filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        report = f"""# RESEARCH REPORT: {title}
Date: {datetime.now().isoformat()}
Author: Prob AI

## Scenario
{scenario}

## Analysis & Results
{result}

## Reasoning History
"""
        for note in memory_notes:
            if "scenario" in note.get("details", {}) and note["details"]["scenario"] == scenario:
                 report += f"- {note['timestamp']}: {note['action']}\n"

        report += "\n## Disclaimer\nThis report was generated by an autonomous AI. Always verify findings with human experts."

        return self.generate_txt(filename, report)
